# dependabot.yml file with updates
# disabled for Docker and limited for npm

version: 2
updates:
  # Configuration for NuGet
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"

  # Configuration for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"